name: 'Unity Project Settings Reader'
description: 'To read and output Unity project settings for the given platform'
author: ''
inputs:
  platform: 
    required: true
    description: 'Build target platform'
    default: 'Android'
runs:
  using: 'node12'
  main: 'dist/index.js'
