name: 'Unity Project Settings Reader'
description: 'To read and output Unity project settings for the given platform'
author: ''
inputs:
  platform: 
    required: true
    description: 'Build target platform'
    default: 'Android'
  projectSettingsPath: 
    required: true
    description: 'Project Settings path'
    default: 'ProjectSettings/ProjectSettings.asset'
  buildPath:
    required: true
    description: 'Build path'
    default: 'build/Android/Android.apk'
  s3BucketName:
    required: true
    description: 'AWS S3 Bucket name'
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'
