name: 'Auto Merge'
on:
  pull_request:

jobs:
  autoMerge: 
    name: Auto Merge PR
    runs-on: ubuntu-latest
    steps: 
      - name: Auto Merge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "build"