name: 'build-test'
on: 
  workflow_dispatch: {}

jobs:
  updateBuilds: #To udpate the builds branch
    name: Update builds branch
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: builds
      - name: Setup Git Config
        id: setupGit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Merge from ${{ github.ref }}
        run: |
          git fetch origin
          git reset --hard origin/${GITHUB_REF#refs/*/}
          git push -f origin builds
  runBuilds: # make sure the action works on a clean machine without building
    needs: updateBuilds
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          # - StandaloneOSX
          # - StandaloneWindows
          # - StandaloneWindows64
          - StandaloneLinux64
          - iOS
          - Android
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: builds
      - name: Setup Git Config
        id: setupGit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Add changes
        id: pushChanges
        run: |
          date > generated.txt
      - name: 'Upload Changes'
        uses: actions/upload-artifact@v2
        with:
          name: changes
          path: generated.txt
          retention-days: 5
  postBuilds: # make sure the action works on a clean machine without building
    needs: runBuilds
    name: Publish changes
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: builds
      - name: Setup Git Config
        id: setupGit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
      - name: Download changes
        uses: actions/download-artifact@v2
        with:
          name: changes
      - name: Add changes
        id: pushChanges
        run: |
          git add .
          git commit -m "generated"
          git push
      - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: Update build
                committer: GitHub <noreply@github.com>
                author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                signoff: false
                base: ${{ github.ref }}
                branch: builds
                delete-branch: true
                title: 'Update build number'
                body: |
                  Update report
                  - Build number
                labels: |
                  build
                draft: false
      # - name: Create pull request
      #   uses: thomaseizinger/create-pull-request@master
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     head: builds
      #     base: ${{ github.ref }}
      #     title: "An automatically created PR!"
