name: 'build-test'
on: 
  workflow_dispatch: {}

jobs:
  updateBuilds: # make sure the action works on a clean machine without building
    name: Update builds ${{ github.ref }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: builds
      - name: Setup Git Config
        id: setupGit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Merge from ${{ github.ref }}
        run: |
          git fetch origin
          git reset --hard origin/${GITHUB_REF#refs/*/}
          git push -f origin builds
  test: # make sure the action works on a clean machine without building
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          # - StandaloneOSX
          # - StandaloneWindows
          # - StandaloneWindows64
          - StandaloneLinux64
          - iOS
          - Android
    steps: 
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     ref: builds
      - name: Setup Git Config
        id: setupGit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Add changes
        id: pushChanges
        run: |
          git pull
          date > generated.txt
          git add .
          git commit -m "generated"
          git push

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: builds
          base: ${{ github.ref }}
          title: "An automatically created PR!"

      # - name: push
      #   uses: github-actions-x/commit@v2.8
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     push-branch: builds
      #     commit-message: '${{ matrix.node-version }} adds auto-generated benchmarks and bar graph'
      #     rebase: 'true' # pull and rebase before commit
      # - name: Default Action  
      #   uses: ./
      #   with:
      #     platform: 'Android'
      #     projectSettingsPath: 'ProjectSettings/ProjectSettings.asset'
      #     buildPath: 'build/Android'
      #     s3BucketName: ${{ secrets.AWS_BUCKET_NAME }}
      #     buildName: 'Sample'
      # - name: get properties
      #   id: json_properties
      #   uses: zoexx/github-action-json-file-properties@release
      #   with:
      #     file_path: "BuildReport.json"
      # - run: |
      #     echo ${{steps.json_properties.outputs.combinedVersionNo}}
      #     echo ${{steps.json_properties.outputs.release}}
      # - name: Sync to S3
      #   uses: JuneSoftware/simple-s3-upload-action@master
      #   with:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
      #     SOURCE_DIR: 'build'
      #     DEST_DIR: 'Android'
      # - name: List all files
      #   id: listFiles
      #   run: |
      #     ls -R
