name: 'build-test'
on: 
  workflow_dispatch: {}

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Default Action  
        uses: ./
        with:
          platform: 'Android'
          path: 'ProjectSettings/ProjectSettings.asset'
      - name: Sync to S3
        uses: raulanatol/aws-s3-docker-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          SOURCE: 'build'
          TARGET: 'Android'
